version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crickathon-db
    restart: always
    environment:
      POSTGRES_USER: crickathon_user
      POSTGRES_PASSWORD: crickathon_password
      POSTGRES_DB: crickathon
    ports:
      - "5432:5432"
    volumes:
      - crickathon-db-data:/var/lib/postgresql/data

volumes:
  crickathon-db-data:
